### ISSUE TITLE
Use this model in an app

### ISSUE THREAD

**Issue by apurva0919** [ColeMurray/age-gender-estimation-tutorial#1]
Can I use this model in an ios app which will detect the age of any person?
Can I convert this model to the core ML model to use it in an ios app to detect the age of any person?

**Comment by ColeMurray** [comment]
@apurva0919,

Yes, you can integrate this Tensorflow model into iOS.
A resource on using Core ML can be found here:
https://hackernoon.com/integrating-tensorflow-model-in-an-ios-app-cecf30b9068d
