### ISSUE TITLE
About InvalidArgumentError  

### ISSUE THREAD

**Issue by robonetphy** [ColeMurray/age-gender-estimation-tutorial#10]
I have run your code with all the requirement file you specified in requirement.txt
but I got InvalidArgumentError error continuously while running same code.
I have just change directory in which data available.you can see that on code.
![image](https://user-images.githubusercontent.com/23169768/60643184-e9956d80-9e4f-11e9-9ce7-0ed775614911.png)
the error occur continuously on 22 line
![image](https://user-images.githubusercontent.com/23169768/60643254-1053a400-9e50-11e9-93f1-cd6ee42ad8a6.png)
you can see here
![image](https://user-images.githubusercontent.com/23169768/60643275-1ba6cf80-9e50-11e9-9213-92e47822fcab.png)
help me out with this.
Thanks in advance

and my system specification is
![image](https://user-images.githubusercontent.com/23169768/60643897-282c2780-9e52-11e9-8393-3c3dec57cea1.png)

**Comment by ColeMurray** [comment]
@robonetphy ,

Can you provide the command you used to initially run the scripts that you were experiencing the ```InvalidArgumentError```

**Comment by robonetphy** [comment]
Aactually I haven't used any command rather than 
python3 train.py 
for training and 
python3 prepocessing.py
since I just replace argument with the variables and pass it as function
for preprocessing.py
    db="mat file link "
    photo="dir of  photo where imdb"
    output="dir of outpur"
    min =1.0
    img=224
    split=0.8

as example similary i have done with train.py
