### ISSUE TITLE
Can this tutorial being used to detect both age and gender in one foreground network

### ISSUE THREAD

**Issue by DanielXu123** [ColeMurray/age-gender-estimation-tutorial#13]
Hi, Cole 

Could you pls upload some testing method and demo trained models?

And, can this model directly predict both age and gender in once computation?

Or .. bascially, this is two seperate network, once for age classification and the other is for gender, and run one by one.

**Comment by ColeMurray** [comment]
Hello @DanielXu123 ,
Unfortunately, I am unable to upload trained models at this time.

Yes, this architecture can be used to predict both age and gender in one call.
