### ISSUE TITLE
Where is the model created?

### ISSUE THREAD

**Issue by FranciscoSola** [ColeMurray/age-gender-estimation-tutorial#16]
Hi Cole, thanks for the tutorial.

I'm a little bit confused about the model we should create. I don't know what path I should use in the parameter --model-cnn when training, I mean I don't have a model file. How do I create it? I found the model-cnn.py file but it contains just some definitions of functions.

Thanks for your help!

**Comment by ColeMurray** [comment]
Hello @FranciscoSola ,

The parameter needed to provide is ```model-dir```. This should be a location where you want to save the model and checkpoints.
https://github.com/ColeMurray/age-gender-estimation-tutorial/blob/master/bin/train.py#L16

**Comment by FranciscoSola** [comment]
Thank you! I could solve it
