### ISSUE TITLE
Use epochs

### ISSUE THREAD

**Issue by RansSelected** [ColeMurray/age-gender-estimation-tutorial#5]
Hi!
| was wondering how is it better to modify the code to use epochs? It seems that for more advanced networks architecture it could make sense. Maybe you do have some ideas, cause I've tried several solutions and it doesn't work properly for me (I'm quite new to Tensorflow and especially to Tensorflow Estimators API).

**Comment by ColeMurray** [comment]
@RansSelected ,

I am unsure I understand the question. Is your question on why to use epochs, or something related to number of epochs and quality of model?
