### ISSUE TITLE
problem during export model

### ISSUE THREAD

**Issue by RiccardoForniz** [ColeMurray/age-gender-estimation-tutorial#7]
Hello everyone,
i have a problem during the export, i got an error as the following: 

line 480, in build_all_signature_defs
    '{}'.format(type(export_outputs)))
ValueError: export_outputs must be a dict and not<class 'NoneType'>

i used your scripts for the entire process, the only difference is that, i don't use Doker.
Did i make any mistakes?

Thanks guys
Ric

**Comment by ColeMurray** [comment]
@RiccardoForniz,

Can you provide additional context on how to reproduce the issue and what commands you ran?
